<a href="https://colab.research.google.com/github/SteeelNerve/TensorFlowTutorial/blob/main/TensorFlowTutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x  # this line is not required unless you are in a notebook
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # this line is not required unless you are in a notebook`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.


In [ ]:
# Initialization of Tensors
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
x = tf.constant([[1,2,3], [4,5,6]])
x = tf.ones((3,3))
x = tf.eye(3) # identity matrix

x = tf.random.normal((3,3),mean=0, stddev=1)
x = tf.random.uniform((1,3), minval=0, maxval=1)
x = tf.range(start=1, limit=10, delta=2)

x = tf.cast(x, dtype=tf.float64)

print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [ ]:
# Mathematical Operations
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x,y)
z = x + y

z = tf.subtract(x,y)

z = tf.tensordot(x,y,axes=1) # element multiplication and summation at the same time

x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
print(z)
z = x @ y
print(z)

tf.Tensor(
[[ 0.8180007 -0.9333291  2.5262308 -0.1169112]
 [ 5.4395795 -1.0505962 -0.0277293 -1.1803695]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.8180007 -0.9333291  2.5262308 -0.1169112]
 [ 5.4395795 -1.0505962 -0.0277293 -1.1803695]], shape=(2, 4), dtype=float32)


In [ ]:
# Indexing
x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

indices = tf.constant([0,3])
x_ind = tf.gather(x,indices)

x = tf.constant([[1,2], [3,4],[5,6]])

print(x[0,:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)


In [ ]:
# Reshaping
x = tf.range(9)
print(x)

x = tf.reshape(x,(3,3))
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
